// <auto-generated />
using System;
using IcyPlay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IcyPlay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915034437_AddPhotoSport")]
    partial class AddPhotoSport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IcyPlay.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("AuditLogs", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookableCourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("HoldsUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hourly");

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("MovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("PlatformHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("ReceiptUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedForVerificationAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookableCourtId");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Bookings", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Bookings.BookingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RateKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CourtId", "Date");

                    b.ToTable("BookingSlots", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Email.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ExternalTemplateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Key")
                        .IsUnique();

                    b.ToTable("EmailTemplates", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9575d6e-7afd-5ed2-9368-fdd45dbf069b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8278054L,
                            IsActive = true,
                            Key = "account-verification",
                            Provider = "Mailjet",
                            Subject = "Verify your IcyPlay email address"
                        },
                        new
                        {
                            Id = new Guid("6b1f2ad4-93c7-4e58-8a0d-1c5e7f9b2d64"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8325458L,
                            IsActive = true,
                            Key = "password-reset",
                            Provider = "Mailjet",
                            Subject = "Reset your IcyPlay password"
                        },
                        new
                        {
                            Id = new Guid("4a7d2f18-6c3b-4a91-b5e0-92d7c1f83b46"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8338524L,
                            IsActive = true,
                            Key = "facility-owner-invitation",
                            Provider = "Mailjet",
                            Subject = "Activate your IcyPlay facility owner account"
                        },
                        new
                        {
                            Id = new Guid("8c4d7f06-9e13-4a52-bd68-2f9a14e07c35"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8347695L,
                            IsActive = true,
                            Key = "facility-attendant-invitation",
                            Provider = "Mailjet",
                            Subject = "{{var:business_name}} has added you as a court attendant"
                        },
                        new
                        {
                            Id = new Guid("b3f61c47-5d28-4e0a-9c73-8a1e5b2049df"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8347566L,
                            IsActive = true,
                            Key = "booking-payment-received",
                            Provider = "Mailjet",
                            Subject = "We have your payment — {{var:facility_name}} is checking it"
                        },
                        new
                        {
                            Id = new Guid("6e94a20d-81cf-4b35-a7e8-3c5d90f61b28"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8347573L,
                            IsActive = true,
                            Key = "booking-payment-submitted",
                            Provider = "Mailjet",
                            Subject = "{{var:customer_name}} has paid for {{var:court_name}} — please confirm"
                        },
                        new
                        {
                            Id = new Guid("d27b5e93-40a6-4c18-b9f2-71e8c3a56d04"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalTemplateId = 8347583L,
                            IsActive = true,
                            Key = "booking-confirmed",
                            Provider = "Mailjet",
                            Subject = "Your court at {{var:facility_name}} is confirmed"
                        });
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Amenities", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6cef6fb-0320-5670-9e7c-2bea98d4f6a4"),
                            Category = "Safety",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "first-aid-kit",
                            Name = "First aid kit"
                        },
                        new
                        {
                            Id = new Guid("c167c9f2-15ac-50a5-a552-22b436a0bff9"),
                            Category = "Safety",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "cctv",
                            Name = "CCTV"
                        },
                        new
                        {
                            Id = new Guid("16557b82-105e-5195-826b-a606259bf214"),
                            Category = "Safety",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "fire-extinguisher",
                            Name = "Fire extinguisher"
                        },
                        new
                        {
                            Id = new Guid("f0ace240-4169-5397-8de9-ceb8972b384c"),
                            Category = "Safety",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "emergency-exit",
                            Name = "Emergency exit"
                        },
                        new
                        {
                            Id = new Guid("a2d94510-2c91-575a-9256-4e17ec0c369c"),
                            Category = "Safety",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 50,
                            IsActive = true,
                            Key = "on-site-staff",
                            Name = "On-site staff"
                        },
                        new
                        {
                            Id = new Guid("27bf719d-50f2-5e76-b392-1897b945e630"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "air-conditioning",
                            Name = "Air conditioning"
                        },
                        new
                        {
                            Id = new Guid("2ee9374d-1467-5426-a912-adebd6240cd0"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "showers",
                            Name = "Showers"
                        },
                        new
                        {
                            Id = new Guid("a98dcb63-d4dc-5211-bf53-693946c22c84"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "lockers",
                            Name = "Lockers"
                        },
                        new
                        {
                            Id = new Guid("afe375ab-a228-5854-9aa7-03382439f85f"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "restrooms",
                            Name = "Restrooms"
                        },
                        new
                        {
                            Id = new Guid("8e87c77b-a8c1-59c3-baf3-081595c7de44"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 50,
                            IsActive = true,
                            Key = "drinking-water",
                            Name = "Drinking water"
                        },
                        new
                        {
                            Id = new Guid("5f10bf74-8ad5-51bb-9694-a12274375c3d"),
                            Category = "Comfort",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 60,
                            IsActive = true,
                            Key = "seating",
                            Name = "Spectator seating"
                        },
                        new
                        {
                            Id = new Guid("b94e2ec5-9db1-5be3-9891-67ded8fa9fcf"),
                            Category = "Access",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "parking",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = new Guid("83b54e86-367e-5fea-a9c8-24fe0b87d58c"),
                            Category = "Access",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "wheelchair-access",
                            Name = "Wheelchair access"
                        },
                        new
                        {
                            Id = new Guid("595960f1-e817-56c6-be96-317fbe21687b"),
                            Category = "Access",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "near-public-transport",
                            Name = "Near public transport"
                        },
                        new
                        {
                            Id = new Guid("3c65a092-7ced-580e-a6bf-592029e433a4"),
                            Category = "Equipment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "racket-rental",
                            Name = "Racket rental"
                        },
                        new
                        {
                            Id = new Guid("ffef0613-d0ac-5150-aec5-7f257da46a7c"),
                            Category = "Equipment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "ball-rental",
                            Name = "Ball rental"
                        },
                        new
                        {
                            Id = new Guid("6015e3d0-73be-51ce-93e6-5dff6362fc79"),
                            Category = "Equipment",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "shuttlecock-for-sale",
                            Name = "Shuttlecock for sale"
                        });
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.BookableCourt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtSportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DivisionNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Whole");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("CourtSportId", "DivisionNumber")
                        .IsUnique();

                    b.ToTable("BookableCourts", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("PeakEndsAt")
                        .HasColumnType("time");

                    b.Property<bool>("PeakOnWeekdays")
                        .HasColumnType("bit");

                    b.Property<bool>("PeakOnWeekends")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("PeakStartsAt")
                        .HasColumnType("time");

                    b.Property<string>("SizeLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SlotLengthMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Surface")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UsesFacilityHours")
                        .HasColumnType("bit");

                    b.Property<string>("VenueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityOwnerId");

                    b.HasIndex("FacilityId", "DisplayOrder");

                    b.ToTable("Courts", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.CourtOperatingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("ClosesAt")
                        .HasColumnType("time");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("OpensAt")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("CourtOperatingHours", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.CourtSport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Divisions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("HolidayRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PeakHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("StandardHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("WeekendRate")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("CourtId", "SportId")
                        .IsUnique();

                    b.ToTable("CourtSports", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SafetyMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FacilityOwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Facilities", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("FacilityId", "AmenityId")
                        .IsUnique();

                    b.ToTable("FacilityAmenities", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityAttendant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FacilityId", "UserId")
                        .IsUnique();

                    b.ToTable("FacilityAttendants", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOperatingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("ClosesAt")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("OpensAt")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("FacilityOperatingHours", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOwnerContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CommencedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(3.00m);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentPublicId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocumentSecureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("DocumentSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FacilityOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PlatformHourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(15.00m);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FacilityOwnerId", "StartDate", "EndDate");

                    b.ToTable("FacilityOwnerContracts", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOwnerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FacilityOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SecureUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FacilityOwnerId", "DocumentType");

                    b.ToTable("FacilityOwnerDocuments", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RepeatsAnnually")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Name", "Date")
                        .IsUnique();

                    b.ToTable("Holidays", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f6bd1a7-9b9c-5d3e-8a1f-11a2b3c4d5e6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 1, 1),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "New Year's Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("5a7ce2b8-acad-5e4f-9b2a-22b3c4d5e6f7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 4, 9),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Araw ng Kagitingan",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("6b8df3c9-bdbe-5f50-ac3b-33c4d5e6f708"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 5, 1),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Labor Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("7c9e04da-cecf-5061-bd4c-44d5e6f70819"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 6, 12),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Independence Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("8daf15eb-dfd0-5172-ce5d-55e6f708192a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 11, 30),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Bonifacio Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("9eb026fc-e0e1-5283-df6e-66f708192a3b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 12, 25),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Christmas Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("afc1370d-f1f2-5394-e07f-7708192a3b4c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 12, 30),
                            IsActive = true,
                            Kind = "Regular",
                            Name = "Rizal Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("b0d2481e-0203-54a5-f180-88192a3b4c5d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 8, 21),
                            IsActive = true,
                            Kind = "Special non-working",
                            Name = "Ninoy Aquino Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("c1e3592f-1314-55b6-0291-992a3b4c5d6e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 11, 1),
                            IsActive = true,
                            Kind = "Special non-working",
                            Name = "All Saints' Day",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("d2f46a30-2425-56c7-13a2-aa3b4c5d6e7f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 12, 8),
                            IsActive = true,
                            Kind = "Special non-working",
                            Name = "Feast of the Immaculate Conception",
                            RepeatsAnnually = true
                        },
                        new
                        {
                            Id = new Guid("e3057b41-3536-57d8-24b3-bb4c5d6e7f80"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateOnly(2026, 12, 31),
                            IsActive = true,
                            Kind = "Special non-working",
                            Name = "Last day of the year",
                            RepeatsAnnually = true
                        });
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.MaintenancePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LiftedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SetByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("FacilityId", "StartsAt", "EndsAt");

                    b.ToTable("MaintenancePeriods", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SecureUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("SportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.HasIndex("CourtId", "SportId");

                    b.HasIndex("FacilityId", "CourtId", "DisplayOrder");

                    b.ToTable("Photos", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Sport");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Sports", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ad5832-6d45-5076-8b4c-d0c79472dd55"),
                            Category = "Court sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "basketball",
                            Kind = "Sport",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("8e21e167-3c31-5e9e-b203-f94339286f02"),
                            Category = "Court sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "volleyball",
                            Kind = "Sport",
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = new Guid("0d37f0cd-9517-5a92-a320-caff82b9bcc6"),
                            Category = "Court sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "futsal",
                            Kind = "Sport",
                            Name = "Futsal"
                        },
                        new
                        {
                            Id = new Guid("c1f88227-155e-5da6-b12b-479ed504e853"),
                            Category = "Court sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "sepak-takraw",
                            Kind = "Sport",
                            Name = "Sepak takraw"
                        },
                        new
                        {
                            Id = new Guid("8bf0905e-65ba-5600-a868-0f28087f1d0b"),
                            Category = "Racket sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "badminton",
                            Kind = "Sport",
                            Name = "Badminton"
                        },
                        new
                        {
                            Id = new Guid("a0f6b01f-491c-5bb0-ad8e-a42f19437ea3"),
                            Category = "Racket sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "tennis",
                            Kind = "Sport",
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("17b95f71-a2b5-50a7-9fde-b07562272bed"),
                            Category = "Racket sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "table-tennis",
                            Kind = "Sport",
                            Name = "Table tennis"
                        },
                        new
                        {
                            Id = new Guid("63573cf8-2b30-57f8-8ead-1da5098ea88e"),
                            Category = "Racket sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "pickleball",
                            Kind = "Sport",
                            Name = "Pickleball"
                        },
                        new
                        {
                            Id = new Guid("dad7ebe3-f916-50f4-9317-92d01c75a061"),
                            Category = "Racket sports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 50,
                            IsActive = true,
                            Key = "squash",
                            Kind = "Sport",
                            Name = "Squash"
                        },
                        new
                        {
                            Id = new Guid("84ed5c9c-3978-56d8-bc1d-9cac5ae1109e"),
                            Category = "Combat",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "boxing",
                            Kind = "Sport",
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = new Guid("f22fc719-1486-5215-9cc9-ec04de119105"),
                            Category = "Combat",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "taekwondo",
                            Kind = "Sport",
                            Name = "Taekwondo"
                        },
                        new
                        {
                            Id = new Guid("2722a749-7853-5d82-a472-5c1ce07862c4"),
                            Category = "Combat",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "karate",
                            Kind = "Sport",
                            Name = "Karate"
                        },
                        new
                        {
                            Id = new Guid("10a110db-d802-51a0-ada1-8f81bc655dcd"),
                            Category = "Combat",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "muay-thai",
                            Kind = "Sport",
                            Name = "Muay Thai"
                        },
                        new
                        {
                            Id = new Guid("babc048a-e8a3-5572-8f03-c5a6a7f57d3f"),
                            Category = "Other",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "fitness",
                            Kind = "Sport",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("aee78495-e295-5753-8b47-de220d9d6f2b"),
                            Category = "Other",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "dance",
                            Kind = "Sport",
                            Name = "Dance"
                        },
                        new
                        {
                            Id = new Guid("441948f8-b6cf-5a23-8074-b45e692b2d73"),
                            Category = "Other",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "yoga",
                            Kind = "Sport",
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = new Guid("1c4f8a2e-5b6d-5c7e-8f90-a1b2c3d4e5f6"),
                            Category = "Events",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            IsActive = true,
                            Key = "birthday-party",
                            Kind = "Event",
                            Name = "Birthday party"
                        },
                        new
                        {
                            Id = new Guid("2d5a9b3f-6c7e-5d8f-9a01-b2c3d4e5f607"),
                            Category = "Events",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 20,
                            IsActive = true,
                            Key = "corporate-event",
                            Kind = "Event",
                            Name = "Corporate event"
                        },
                        new
                        {
                            Id = new Guid("3e6bac40-7d8f-5e90-ab12-c3d4e5f60718"),
                            Category = "Events",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 30,
                            IsActive = true,
                            Key = "tournament",
                            Kind = "Event",
                            Name = "Tournament"
                        },
                        new
                        {
                            Id = new Guid("4f7cbd51-8e90-5fa1-bc23-d4e5f6071829"),
                            Category = "Events",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 40,
                            IsActive = true,
                            Key = "training-clinic",
                            Kind = "Event",
                            Name = "Training clinic"
                        },
                        new
                        {
                            Id = new Guid("5a8dce62-9fa1-50b2-cd34-e5f60718293a"),
                            Category = "Events",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 50,
                            IsActive = true,
                            Key = "concert-or-show",
                            Kind = "Event",
                            Name = "Concert or show"
                        });
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.AccountInvitationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("AccountInvitationTokens", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("EmailVerificationTokens", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.FacilityOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GcashAccountName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GcashNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GcashQrCodeUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartialBookingExpiryMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FacilityOwners", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("PasswordResetTokens", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.PlatformAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlatformAdmins", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("IcyPlay.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.BookableCourt", "BookableCourt")
                        .WithMany()
                        .HasForeignKey("BookableCourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookableCourt");
                });

            modelBuilder.Entity("IcyPlay.Domain.Bookings.BookingSlot", b =>
                {
                    b.HasOne("IcyPlay.Domain.Bookings.Booking", "Booking")
                        .WithMany("Slots")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.BookableCourt", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IcyPlay.Domain.Facilities.CourtSport", "CourtSport")
                        .WithMany("BookableCourts")
                        .HasForeignKey("CourtSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("CourtSport");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Court", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany("Courts")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.CourtOperatingHour", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Court", "Court")
                        .WithMany("OperatingHours")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.CourtSport", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Court", "Court")
                        .WithMany("Sports")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcyPlay.Domain.Facilities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Facility", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.FacilityOwner", "FacilityOwner")
                        .WithMany("Facilities")
                        .HasForeignKey("FacilityOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityOwner");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityAmenity", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany("Amenities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityAttendant", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany("Attendants")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOperatingHour", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany("OperatingHours")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOwnerContract", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.FacilityOwner", "FacilityOwner")
                        .WithMany("Contracts")
                        .HasForeignKey("FacilityOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityOwner");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.FacilityOwnerDocument", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.FacilityOwner", "FacilityOwner")
                        .WithMany("Documents")
                        .HasForeignKey("FacilityOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityOwner");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.MaintenancePeriod", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Photo", b =>
                {
                    b.HasOne("IcyPlay.Domain.Facilities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IcyPlay.Domain.Facilities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcyPlay.Domain.Facilities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Court");

                    b.Navigation("Facility");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.AccountInvitationToken", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany("AccountInvitationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.Customer", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("IcyPlay.Domain.Identity.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.EmailVerificationToken", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.FacilityOwner", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("IcyPlay.Domain.Identity.FacilityOwner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.PlatformAdmin", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("IcyPlay.Domain.Identity.PlatformAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("IcyPlay.Domain.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IcyPlay.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Court", b =>
                {
                    b.Navigation("OperatingHours");

                    b.Navigation("Sports");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.CourtSport", b =>
                {
                    b.Navigation("BookableCourts");
                });

            modelBuilder.Entity("IcyPlay.Domain.Facilities.Facility", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Attendants");

                    b.Navigation("Courts");

                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.FacilityOwner", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Documents");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("IcyPlay.Domain.Identity.User", b =>
                {
                    b.Navigation("AccountInvitationTokens");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
